INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Alabama');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Alaska');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Arizona');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Arkansas');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'California');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Colorado');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Connecticut');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Delaware');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Florida');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Georgia');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Hawaii');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Idaho');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Illinois');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Indiana');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Iowa');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Kansas');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Kentucky');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Louisiana');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Maine');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Maryland');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Massachusetts');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Michigan');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Minnesota');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Mississippi');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Missouri');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Montana');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Nebraska');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Nevada');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'New Hampshire');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'New Jersey');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'New Mexico');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'New York');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'North Carolina');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'North Dakota');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Ohio');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Oklahoma');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Oregon');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Pennsylvania');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Rhode Island');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'South Carolina');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'South Dakota');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Tennessee');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Texas');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Utah');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Vermont');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Virginia');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Washington province');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'West Virginia');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Wisconsin');
INSERT INTO locations (country, iso_code, region, subregion, state_province) VALUES ('USA', 'US', 'Americas', 'North America', 'Wyoming');
